# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "estum: ruby dev"
email: jessejuz@gmail.com
description: >
  Tõnis Simo's personal homepage & blog about ruby development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://estum.github.io" # the base hostname & protocol for your site
repository: estum/estum.github.io
twitter_username: jessejuz
github_username:  estum

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-github-metadata